version: '3'
services:
  db:
    image: mysql:8
    container_name: movie-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moviedb
    networks:
      - movie-network

  backend:
    build: ./backend
    container_name: movie-backend
    ports:
      - "5000:5000"
    networks:
      - movie-network

  frontend:
    image: nginx
    container_name: movie-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - movie-network

networks:
  movie-network:
